# Generated by Django 2.2.3 on 2020-04-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_salary', models.IntegerField(blank=True, null=True)),
                ('doctor_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('doctor_shift_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NurseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('nurse_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('nurse_salary', models.IntegerField(blank=True, null=True)),
                ('nurse_shift_type', models.CharField(blank=True, max_length=255, null=True)),
                ('nurse_shift_duration', models.IntegerField(blank=True, null=True)),
                ('doctor_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.DoctorData')),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fname', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_lname', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('patient_relative_ph_no', models.CharField(blank=True, max_length=12, null=True)),
                ('patient_diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('nurse_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.NurseData')),
            ],
        ),
    ]
