# Generated by Django 2.2.3 on 2020-04-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='patient_doctor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.DoctorData'),
        ),
    ]
