# Generated by Django 2.2.3 on 2020-04-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_patientdata_patient_doctor_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='patient_doctor_fk',
        ),
    ]
